apiVersion: batch/v1
kind: Job
metadata:
  name: failed-job

spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: check
        image: nginx:latest
        command: ["some-nonexistent-command"]  # This command does not exist, causing failure
      restartPolicy: Never