apiVersion: apps/v1
kind: Deployment
metadata:
  name: retry-deploy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retry-deploy-app
  template:
    metadata:
      labels:
        app: retry-deploy-app
    spec:
      containers:
      - name: app
        image: nginx:xyz