apiVersion: batch/v1
kind: Job
metadata:
  name: post-deploy-check
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookFailed

spec:
  template:
    spec:
      containers:
      - name: check
        image: nginx:latest
        command: ["sh", "-c", "gashg 'App is healthy, Sent mail...' && exit 0"]
        # command: ["some-nonexistent-command"]  # This command does not exist, causing failure
      restartPolicy: Never