apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-helm-pvt
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://r-kalyan-r.github.io/argocd-tutorial/  # PVT Helm repo
    chart: helm-nginx-demo  # The chart name
    targetRevision: 0.1.0  # Chart version
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
