apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-updator
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: myimage=docker.io/rapkalya/webapp
    argocd-image-updater.argoproj.io/myimage.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/myimage.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/myimage.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: git@github.com:r-kalyan-r/argocd-tutorial.git
    path: image-updator   # 👈 your chart folder
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
