apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:r-kalyan-r/argocd-tutorial.git'
    targetRevision: HEAD
    path: kustomize-app/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
