apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terraform-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:r-kalyan-r/argocd-tutorial.git'
    targetRevision: HEAD
    path: terraform-app/apps
    plugin:
      name: terraform
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
