apiVersion: batch/v1
kind: Job
metadata:
  name: failed-job
  # annotations:
  #   argocd.argoproj.io/hook: Sync
  #   argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 0  # No retries by Kubernetes
  template:
    spec:
      containers:
      - name: check
        image: nginx:latest
        command: ["some-nonexistent-command"]  # This command does not exist, causing failure
      restartPolicy: Never
