apiVersion: batch/v1
kind: Job
metadata:
  name: post-deploy-check
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    spec:
      containers:
      - name: check
        image: rabbitmq:latest
      restartPolicy: Never