apiVersion: batch/v1
kind: Job
metadata:
  name: pre-db-migration
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: postgres:latest
        env:  # env should be inside the container
        - name: POSTGRES_PASSWORD
          value: "test123"
        - name: POSTGRES_USER
          value: "test123"
        - name: POSTGRES_DB
          value: "test"
      restartPolicy: Never
