# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: application
  annotations:
    argocd.argoproj.io/sync-wave: "2" # Sync wave for Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app-container
        image: nginx:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: app-config
