apiVersion: apps/v1
kind: Deployment
metadata:
  names: rollback
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rollback-app
  template:
    metadata:
      labels:
        app: rollback-app
    spec:
      containers:
      - name: app
        image: nginx:latest