apiVersion: v1
kind: ConfigMap
metadata:
  name: terraform-plugin-config
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: terraform
    spec:
      version: v1.0
      init:
        command: ["/bin/sh", "-c"]
        args: ["terraform init -input=false"]
      generate:
        command: ["/bin/sh", "-c"]
        args: ["terraform plan -out=tfplan -input=false && terraform show -json tfplan | tf2yaml"]
